Traceback (most recent call last):
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\52377\AppData\Local\Programs\Python\Python313\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pubchem_smiles_by_name("ibuprofen")
------------------


[31m---------------------------------------------------------------------------[39m
[31mHTTPError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[20][39m[32m, line 5[39m, in [36msafe_get[39m[34m(url, timeout)[39m
[32m      4[39m r = requests.get(url, timeout=timeout)
[32m----> [39m[32m5[39m [43mr[49m[43m.[49m[43mraise_for_status[49m[43m([49m[43m)[49m
[32m      6[39m [38;5;28;01mreturn[39;00m r.json()

[36mFile [39m[32m~\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py:1026[39m, in [36mResponse.raise_for_status[39m[34m(self)[39m
[32m   1025[39m [38;5;28;01mif[39;00m http_error_msg:
[32m-> [39m[32m1026[39m     [38;5;28;01mraise[39;00m HTTPError(http_error_msg, response=[38;5;28mself[39m)

[31mHTTPError[39m: 400 Client Error: PUGREST.BadRequest for url: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/ibuprofen/property/CanonicalSMILES,IsomericSMILES,CID,IUPACName/JSON

The above exception was the direct cause of the following exception:

[31mValueError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[22][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [43mpubchem_smiles_by_name[49m[43m([49m[33;43m"[39;49m[33;43mibuprofen[39;49m[33;43m"[39;49m[43m)[49m

[36mCell[39m[36m [39m[32mIn[21][39m[32m, line 11[39m, in [36mpubchem_smiles_by_name[39m[34m(name, isomeric)[39m
[32m      9[39m encoded = quote_plus([38;5;28mstr[39m(name).strip())
[32m     10[39m url = [33mf[39m[33m"[39m[33mhttps://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/[39m[38;5;132;01m{[39;00mencoded[38;5;132;01m}[39;00m[33m/property/[39m[38;5;132;01m{[39;00mfields[38;5;132;01m}[39;00m[33m/JSON[39m[33m"[39m
[32m---> [39m[32m11[39m data = [43msafe_get[49m[43m([49m[43murl[49m[43m)[49m
[32m     12[39m [38;5;28;01mtry[39;00m:
[32m     13[39m     p = data[[33m"[39m[33mPropertyTable[39m[33m"[39m][[33m"[39m[33mProperties[39m[33m"[39m][[32m0[39m]

[36mCell[39m[36m [39m[32mIn[20][39m[32m, line 8[39m, in [36msafe_get[39m[34m(url, timeout)[39m
[32m      6[39m     [38;5;28;01mreturn[39;00m r.json()
[32m      7[39m [38;5;28;01mexcept[39;00m requests.exceptions.HTTPError [38;5;28;01mas[39;00m e:
[32m----> [39m[32m8[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33mf[39m[33m"[39m[33mHTTP error from PubChem. URL was:[39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00murl[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[33mMessage: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[33m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01me[39;00m
[32m      9[39m [38;5;28;01mexcept[39;00m requests.exceptions.RequestException [38;5;28;01mas[39;00m e:
[32m     10[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33mf[39m[33m"[39m[33mNetwork error while contacting PubChem: [39m[38;5;132;01m{[39;00me[38;5;132;01m}[39;00m[33m"[39m) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01me[39;00m

[31mValueError[39m: HTTP error from PubChem. URL was:
https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/ibuprofen/property/CanonicalSMILES,IsomericSMILES,CID,IUPACName/JSON
Message: 400 Client Error: PUGREST.BadRequest for url: https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/ibuprofen/property/CanonicalSMILES,IsomericSMILES,CID,IUPACName/JSON

