Traceback (most recent call last):
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "c:\users\52377\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if torch is not None:
    # Embed the dataset and visualize with t-SNE to 2D
    enc_chem.eval()
    with torch.no_grad():
        Z_chem = enc_chem(torch.from_numpy(X_chem4d)).cpu().numpy()
    show_shape("Z_chem", Z_chem)

    Z_chem_small, label_small = Z_chem, label

    tsne = TSNE(
        n_components=2,
        perplexity=2,
        learning_rate="auto",
        init="pca",
        max_iter=250,
        random_state=0
    )
    Z2 = tsne.fit_transform(Z_chem_small)

    plt.figure(figsize=(6, 5))
    plt.scatter(Z2[label_small==1, 0], Z2[label_small==1, 1], alpha=0.6, label="label 1")
    plt.scatter(Z2[label_small==0, 0], Z2[label_small==0, 1], alpha=0.6, label="label 0")
    plt.title("t-SNE of chemistry embedding")
    plt.legend()
    plt.tight_layout()
    plt.show()


------------------

----- stdout -----
Z_chem.shape: (1500, 8)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[27], line 10[0m
[0;32m      6[0m show_shape([38;5;124m"[39m[38;5;124mZ_chem[39m[38;5;124m"[39m, Z_chem)
[0;32m      8[0m Z_chem_small, label_small [38;5;241m=[39m Z_chem, label
[1;32m---> 10[0m tsne [38;5;241m=[39m [43mTSNE[49m[43m([49m
[0;32m     11[0m [43m    [49m[43mn_components[49m[38;5;241;43m=[39;49m[38;5;241;43m2[39;49m[43m,[49m
[0;32m     12[0m [43m    [49m[43mperplexity[49m[38;5;241;43m=[39;49m[38;5;241;43m2[39;49m[43m,[49m
[0;32m     13[0m [43m    [49m[43mlearning_rate[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mauto[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m     14[0m [43m    [49m[43minit[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mpca[39;49m[38;5;124;43m"[39;49m[43m,[49m
[0;32m     15[0m [43m    [49m[43mmax_iter[49m[38;5;241;43m=[39;49m[38;5;241;43m250[39;49m[43m,[49m
[0;32m     16[0m [43m    [49m[43mrandom_state[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m
[0;32m     17[0m [43m[49m[43m)[49m
[0;32m     18[0m Z2 [38;5;241m=[39m tsne[38;5;241m.[39mfit_transform(Z_chem_small)
[0;32m     20[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m6[39m, [38;5;241m5[39m))

[1;31mTypeError[0m: __init__() got an unexpected keyword argument 'max_iter'

