Traceback (most recent call last):
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "c:\users\52377\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\52377\appdata\local\programs\python\python38\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pyvis.network import Network
from urllib import parse
g = Network(notebook=True,height='600px',width='800px')
for i,smi in enumerate(net.nodes):
    qsmi = parse.quote(smi)
    imgurl = f"https://mol-renderer2-dev.t5ix.io/to_img/mol.png?smiles={qsmi}&w=200&h=150"
    g.add_node(i,shape="image",label=' ',
               image =imgurl, title=f'<img src="{imgurl}"/>')
for e in net.edges:
    g.add_edge(e.beginIdx,e.endIdx,label=str(e.type))
g.show("basic.html")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[4], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mpyvis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnetwork[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Network
[0;32m      2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01murllib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m parse
[0;32m      3[0m g [38;5;241m=[39m Network(notebook[38;5;241m=[39m[38;5;28;01mTrue[39;00m,height[38;5;241m=[39m[38;5;124m'[39m[38;5;124m600px[39m[38;5;124m'[39m,width[38;5;241m=[39m[38;5;124m'[39m[38;5;124m800px[39m[38;5;124m'[39m)

[1;31mModuleNotFoundError[0m: No module named 'pyvis'

